# Window behavior

remember_window_size no
initial_window_width 128c
initial_window_height 32c

background_opacity 0.92
dynamic_background_opacity yes

# Enough space to see split borders without wasting terminal area.
window_margin_width 1 1 0 0
window_padding_width 4

enabled_layouts splits,tall,stack
scrollback_lines 4000
copy_on_select clipboard

# Do not ask for confirmation when closing a normal terminal window.
confirm_os_window_close 0

